/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * importTextHelper.java
 *
 * Created on Jul 17, 2009, 8:33:56 PM
 */

package ledworks4;

/**
 *
 * @author Electrics Dept
 */
public class importTextHelper extends javax.swing.JFrame {
    int date = 0;
    int time = 1;
    int groups = 2;
    int prize = 3;
    int genome = 4;
    int guy = 5;
    int birthday = 6;
    int headache = 7;
    int facebook = 8;
    /** Creates new form importTextHelper */
    public importTextHelper() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        nameArea = new javax.swing.JTextArea();
        importButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ledworks4.LEDWorks4App.class).getContext().getResourceMap(importTextHelper.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        nameArea.setColumns(20);
        nameArea.setRows(5);
        nameArea.setName("nameArea"); // NOI18N
        jScrollPane1.setViewportView(nameArea);

        importButton.setText(resourceMap.getString("importButton.text")); // NOI18N
        importButton.setName("importButton"); // NOI18N
        importButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(importButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importButtonMouseClicked
        // TODO add your handling code here:
        String[] dataLines = nameArea.getText().split("\n");
        String[][] dataRecord = new String[dataLines.length][];
        for (int i = 0; i < dataLines.length; i++){
            dataRecord[i] = dataLines[i].split("\u0009");
        }
        nameArea.setText("Clear \n");
        for (int q = 0; q < dataRecord.length; q++){
            for (int w = 0; w < dataRecord[q].length; w++){
                nameArea.append(dataRecord[q][w] + "\u0009" );
            }
            nameArea.append("\n");
        }
        
}//GEN-LAST:event_importButtonMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new importTextHelper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton importButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea nameArea;
    // End of variables declaration//GEN-END:variables

}
