/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * rndChooser.java
 *
 * Created on Mar 3, 2010, 2:52:58 PM
 */
import java.util.Random;
/**
 *
 * @author Electrics Dept
 */
public class rndChooser extends javax.swing.JFrame {
    int i = 0;
    int limit = 0;
    int[] tracker = new int[36];
    /** Creates new form rndChooser */
    public rndChooser() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spinButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        spinText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ledworks4.LEDWorks4App.class).getContext().getResourceMap(rndChooser.class);
        spinButton.setText(resourceMap.getString("spinButton.text")); // NOI18N
        spinButton.setName("spinButton"); // NOI18N
        spinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spinButtonMouseClicked(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        spinText.setColumns(20);
        spinText.setRows(5);
        spinText.setName("spinText"); // NOI18N
        jScrollPane1.setViewportView(spinText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(spinButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinButtonMouseClicked
        // TODO add your handling code here:
        trySpin();
    }//GEN-LAST:event_spinButtonMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rndChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton spinButton;
    private javax.swing.JTextArea spinText;
    // End of variables declaration//GEN-END:variables
    /** Generates a random number between 0 and 36
     *  and tracks to avoid duplicates over 36 rolls 
     */
    private void trySpin(){
        tracker[i] = spinner();
        limit = i;
        for (int j = 0; j < limit; j++){
            /*spinText.append(tracker[j] + " = " + tracker [i] + "\n");*/
            if (tracker[j] == tracker[i]){
                tracker[i] = spinner();
            }
        }
        spinText.append(tracker[i] + " ");
        /*spinText.append("(" + i + ") ");
        spinText.append("L"+ limit + "\n");
        spinText.append("size=" + tracker.length + "\n");*/
        i++;
        if (i == tracker.length){
            i = 0;
        }
    }
    /** Generates a random number between 0 and
     *  upperLimit and tracks to avoid duplicates
     *  for 36 "rolls"
     */
    private void trySpin(int upperLimit){
        tracker[i] = spinner(upperLimit);
        limit = i;
        for (int j = 0; j < limit; j++){
            if (tracker[j] == tracker[i]){
                tracker[i] = spinner();
            }
        }
        spinText.append(tracker[i] + " ");
        i++;
        if (i == tracker.length){
            i = 0;
        }
    }
    /** Generates a random number between 0 - 36 */
    private int spinner(){
        Random generator = new Random();
        int randomNumber = generator.nextInt(37);
        return randomNumber;
    }
    /** Generates a random number between 0 - range */
    public int spinner(int range){
        Random generator = new Random();
        int randomNumber = generator.nextInt(range);
        return randomNumber;
    }
}
